const eventosPadrao = [
    {
        id: 1,
        title: 'Prova de Matemática',
        start: new Date(2024, 2, 19, 9, 0),
        end: new Date(2024, 2, 19, 11, 0),
        desc: 'Prova de Matemática para o 1º período',
        color: 'blue',
        tipo: 'Prova',
    },
    {
        id: 2,
        title: 'Aniversário do Pai',
        start: new Date(2024, 3, 5, 18, 0),
        end: new Date(2024, 3, 5, 22, 0),
        desc: 'Celebrar o aniversário do pai com a família',
        color: '#f15550',
        tipo: 'Aniversário',
    },
    {
        id: 3,
        title: 'Apresentação de Trabalho de Biologia',
        start: new Date(2024, 4, 10, 14, 0),
        end: new Date(2024, 4, 10, 16, 0),
        desc: 'Apresentação sobre a biodiversidade marinha',
        color: 'green',
        tipo: 'Apresentação',
    },
    {
        id: 4,
        title: 'Seminário de História',
        start: new Date(2024, 5, 15, 10, 0),
        end: new Date(2024, 5, 15, 12, 0),
        desc: 'Seminário sobre a Revolução Francesa',
        color: 'purple',
        tipo: 'Seminário',
    },
    {
        id: 5,
        title: 'Dar aula de Física',
        start: new Date(2024, 6, 20, 8, 0),
        end: new Date(2024, 6, 20, 10, 0),
        desc: 'Aula sobre mecânica clássica',
        color: 'orange',
        tipo: 'aula',
    },
    {
        id: 6,
        title: 'Entrega de Projeto de Química',
        start: new Date(2024, 7, 25, 15, 0),
        end: new Date(2024, 7, 25, 17, 0),
        desc: 'Prazo final para entrega do projeto de síntese orgânica',
        color: 'cyan',
        tipo: 'Projeto',
    },
    {
        id: 7,
        title: 'Reunião de Pais e Professores',
        start: new Date(2024, 8, 1, 18, 0),
        end: new Date(2024, 8, 1, 20, 0),
        desc: 'Discussão do desempenho dos alunos',
        color: 'pink',
        tipo: 'Reunião',
    },
    {
        id: 8,
        title: 'Exposição de Arte',
        start: new Date(2024, 9, 10, 10, 0),
        end: new Date(2024, 9, 10, 16, 0),
        desc: 'Visita à exposição de arte contemporânea',
        color: 'brown',
        tipo: 'Arte',
    },
    {
        id: 9,
        title: 'Apresentação de Dança',
        start: new Date(2024, 10, 15, 19, 0),
        end: new Date(2024, 10, 15, 21, 0),
        desc: 'Apresentação de balé clássico',
        color: 'lime',
        tipo: 'Arte',
    },
    {
        id: 10,
        title: 'Concerto de Música Clássica',
        start: new Date(2024, 11, 1, 20, 0),
        end: new Date(2024, 11, 1, 22, 0),
        desc: 'Concerto da Orquestra Sinfônica',
        color: 'teal',
        tipo: 'Arte',
    },
    {
        id: 11,
        title: 'Entrega de TCC',
        start: new Date(2024, 11, 20, 12, 0),
        end: new Date(2024, 11, 20, 14, 0),
        desc: 'Prazo final para entrega do Trabalho de Conclusão de Curso',
        color: 'maroon',
        tipo: 'Faculdade',
    },
    {
        id: 12,
        title: 'Apresentação de Teatro',
        start: new Date(2024, 11, 28, 16, 0),
        end: new Date(2024, 11, 28, 18, 0),
        desc: 'Peça teatral "Romeu e Julieta"',
        color: 'olive',
        tipo: 'Arte',
    },
    {
        id: 13,
        title: 'Entrega de Relatório de Pesquisa',
        start: new Date(2024, 0, 15, 9, 0),
        end: new Date(2024, 0, 15, 11, 0),
        desc: 'Prazo final para entrega do relatório de pesquisa científica',
        color: 'navy',
        tipo: 'Faculdade',
    },
    {
        id: 14,
        title: 'Conferência de Tecnologia',
        start: new Date(2024, 1, 10, 14, 0),
        end: new Date(2024, 1, 10, 16, 0),
        desc: 'Participação na conferência sobre inteligência artificial',
        color: 'silver',
        tipo: 'Faculdade',
    },
    {
        id: 15,
        title: 'Entrega de Proposta de Negócio',
        start: new Date(2024, 2, 5, 11, 0),
        end: new Date(2024, 2, 5, 13, 0),
        desc: 'Prazo final para entrega da proposta de startup',
        color: 'gold',
        tipo: 'Faculdade',
    },
    {
        id: 16,
        title: 'Apresentação de Projeto de Arquitetura',
        start: new Date(2024, 3, 1, 10, 0),
        end: new Date(2024, 3, 1, 12, 0),
        desc: 'Apresentação do projeto de revitalização urbana',
        color: 'indigo',
        tipo: 'Faculdade',
    },
    {
        id: 17,
        title: 'Reunião de Equipe',
        start: new Date(2024, 4, 5, 15, 0),
        end: new Date(2024, 4, 5, 17, 0),
        desc: 'Discussão sobre metas trimestrais',
        color: 'crimson',
        tipo: 'Faculdade',
    },
    {
        id: 18,
        title: 'Encontro de Escritores',
        start: new Date(2024, 5, 10, 18, 0),
        end: new Date(2024, 5, 10, 20, 0),
        desc: 'Discussão de técnicas de escrita criativa',
        color: 'darkgreen',
        tipo: 'Escritores',
    },
    {
        id: 19,
        title: 'Entrega de Artigo Científico',
        start: new Date(2024, 6, 5, 9, 0),
        end: new Date(2024, 6, 5, 11, 0),
        desc: 'Prazo final para submissão do artigo para conferência',
        color: 'darkorange',
        tipo: 'Faculdade',
    },
    {
        id: 20,
        title: 'Sessão de Cinema ao Ar Livre',
        start: new Date(2024, 7, 5, 20, 0),
        end: new Date(2024, 7, 5, 22, 0),
        desc: 'Exibição do filme clássico "Cidadão Kane"',
        color: 'darkred',
        tipo: 'Arte',
    },
    {
        id: 21,
        title: 'Apresentação de Palestra',
        start: new Date(2024, 8, 1, 14, 0),
        end: new Date(2024, 8, 1, 16, 0),
        desc: 'Palestra sobre empreendedorismo e inovação',
        color: 'darkviolet',
        tipo: 'Faculdade',
    },
    {
        id: 22,
        title: 'Workshop de Fotografia',
        start: new Date(2024, 9, 10, 10, 0),
        end: new Date(2024, 9, 10, 12, 0),
        desc: 'Workshop prático sobre composição fotográfica',
        color: 'deeppink',
        tipo: 'Workshop',
    },
    {
        id: 23,
        title: 'Entrega de Tarefa de Programação',
        start: new Date(2024, 10, 5, 11, 0),
        end: new Date(2024, 10, 5, 13, 0),
        desc: 'Prazo final para entrega da tarefa de algoritmos',
        color: 'firebrick',
        tipo: 'Faculdade',
    },
    {
        id: 24,
        title: 'Apresentação de Pitch de Negócio',
        start: new Date(2024, 11, 1, 16, 0),
        end: new Date(2024, 11, 1, 18, 0),
        desc: 'Apresentação do pitch para investidores',
        color: 'forestgreen',
        tipo: 'Apresentação',
    },
    {
        id: 25,
        title: 'Simulado de Enem',
        start: new Date(2024, 0, 20, 9, 0),
        end: new Date(2024, 0, 20, 13, 0),
        desc: 'Simulado para os estudantes do ensino médio',
        color: 'gold',
        tipo: 'Enem',
    },
    {
        id: 26,
        title: 'Curso de Liderança',
        start: new Date(2024, 1, 15, 14, 0),
        end: new Date(2024, 1, 15, 18, 0),
        desc: 'Participação no curso sobre habilidades de liderança',
        color: 'greenyellow',
        tipo: 'Workshop',
    },
    {
        id: 27,
        title: 'Apresentação de Tese de Doutorado',
        start: new Date(2024, 2, 10, 10, 0),
        end: new Date(2024, 2, 10, 12, 0),
        desc: 'Defesa da tese na banca examinadora',
        color: 'hotpink',
        tipo: 'Faculdade',
    },
    {
        id: 28,
        title: 'Entrega de Redação',
        start: new Date(2024, 3, 5, 9, 0),
        end: new Date(2024, 3, 5, 11, 0),
        desc: 'Prazo final para entrega da redação',
        color: 'indigo',
        tipo: 'Enem',
    },
    {
        id: 29,
        title: 'Apresentação de Case de Marketing',
        start: new Date(2024, 4, 10, 15, 0),
        end: new Date(2024, 4, 10, 17, 0),
        desc: 'Apresentação do case de sucesso da campanha publicitária',
        color: 'khaki',
        tipo: 'Apresentação',
    },
    {
        id: 30,
        title: 'Workshop de Desenvolvimento Pessoal',
        start: new Date(2024, 5, 5, 11, 0),
        end: new Date(2024, 5, 5, 13, 0),
        desc: 'Workshop sobre autoconhecimento e desenvolvimento pessoal',
        color: 'lavender',
        tipo: 'Workshop',
    },
    {
        id: 31,
        title: 'Exposição de Fotografia',
        start: new Date(2024, 6, 5, 10, 0),
        end: new Date(2024, 6, 5, 16, 0),
        desc: 'Visita à exposição de fotografia contemporânea',
        color: 'lightblue',
        tipo: 'Arte',
    },
    {
        id: 32,
        title: 'Conferência de Educação',
        start: new Date(2024, 7, 1, 14, 0),
        end: new Date(2024, 7, 1, 16, 0),
        desc: 'Participação na conferência sobre novas metodologias de ensino',
        color: 'lightcoral',
        tipo: 'Faculdade',
    },
    {
        id: 33,
        title: 'Apresentação de Demonstração de Software',
        start: new Date(2024, 8, 5, 16, 0),
        end: new Date(2024, 8, 5, 18, 0),
        desc: 'Demonstração do novo software de gestão',
        color: 'lightgreen',
        tipo: 'Faculdade',
    },
    {
        id: 34,
        title: 'Entrega de Trabalho em Grupo',
        start: new Date(2024, 9, 5, 9, 0),
        end: new Date(2024, 9, 5, 11, 0),
        desc: 'Prazo final para entrega do trabalho em grupo de sociologia',
        color: 'lightpink',
        tipo: 'Faculdade',
    },
    {
        id: 35,
        title: 'Concerto de Jazz',
        start: new Date(2024, 10, 1, 20, 0),
        end: new Date(2024, 10, 1, 22, 0),
        desc: 'Concerto da Big Band da cidade',
        color: 'lightsalmon',
        tipo: 'Arte',
    },
    {
        id: 36,
        title: 'Apresentação de Case de Estudo',
        start: new Date(2024, 11, 5, 14, 0),
        end: new Date(2024, 11, 5, 16, 0),
        desc: 'Apresentação do case de estudo de mercado',
        color: 'lightseagreen',
        tipo: 'Faculdade',
    },
    {
        id: 37,
        title: 'Entrega de Artigo Acadêmico',
        start: new Date(2024, 0, 10, 11, 0),
        end: new Date(2024, 0, 10, 13, 0),
        desc: 'Prazo final para entrega do artigo para revista científica',
        color: 'lightskyblue',
        tipo: 'Faculdade',
    },
    {
        id: 38,
        title: 'Exposição de Esculturas',
        start: new Date(2024, 1, 5, 10, 0),
        end: new Date(2024, 1, 5, 16, 0),
        desc: 'Visita à exposição de esculturas contemporâneas',
        color: 'lightsteelblue',
        tipo: 'Arte',
    },
    {
        id: 39,
        title: 'Apresentação de Debate',
        start: new Date(2024, 2, 1, 15, 0),
        end: new Date(2024, 2, 1, 17, 0),
        desc: 'Debate sobre questões ambientais',
        color: 'lightyellow',
        tipo: 'Faculdade',
    },
    {
        id: 40,
        title: 'Entrega de Projeto de Engenharia',
        start: new Date(2024, 3, 5, 9, 0),
        end: new Date(2024, 3, 5, 11, 0),
        desc: 'Prazo final para entrega do projeto estrutural',
        color: 'lime',
        tipo: 'Faculdade',
    },
    {
        id: 41,
        title: 'Apresentação de Workshop de Marketing Digital',
        start: new Date(2024, 4, 1, 16, 0),
        end: new Date(2024, 4, 1, 18, 0),
        desc: 'Workshop prático sobre estratégias de marketing online',
        color: 'magenta',
        tipo: 'Workshop',
    },
    {
        id: 42,
        title: 'Sessão de Leitura de Poesia',
        start: new Date(2024, 5, 5, 19, 0),
        end: new Date(2024, 5, 5, 21, 0),
        desc: 'Leitura de poemas de autores locais',
        color: 'midnightblue',
        tipo: 'Arte',
    },
    {
        id: 43,
        title: 'Entrega de Relatório de Estágio',
        start: new Date(2024, 6, 10, 11, 0),
        end: new Date(2024, 6, 10, 13, 0),
        desc: 'Prazo final para entrega do relatório de estágio supervisionado',
        color: 'mintcream',
        tipo: 'Faculdade',
    },
    {
        id: 44,
        title: 'Concerto de Ópera',
        start: new Date(2024, 7, 5, 20, 0),
        end: new Date(2024, 7, 5, 22, 0),
        desc: 'Apresentação da ópera "Carmen"',
        color: 'mistyrose',
        tipo: 'Arte',
    },
    {
        id: 45,
        title: 'Apresentação de Workshop de Vendas',
        start: new Date(2024, 8, 1, 14, 0),
        end: new Date(2024, 8, 1, 16, 0),
        desc: 'Workshop prático sobre técnicas de vendas',
        color: 'moccasin',
        tipo: 'Workshop',
    },
    {
        id: 46,
        title: 'Entrega de Artigo de Opinião',
        start: new Date(2024, 9, 5, 9, 0),
        end: new Date(2024, 9, 5, 11, 0),
        desc: 'Prazo final para entrega do artigo para jornal local',
        color: 'navajowhite',
        tipo: 'Faculdade',
    },
    {
        id: 47,
        title: 'Apresentação de Mostra de Cinema',
        start: new Date(2024, 10, 5, 16, 0),
        end: new Date(2024, 10, 5, 18, 0),
        desc: 'Mostra de cinema independente',
        color: 'oldlace',
        tipo: 'Arte',
    },
    {
        id: 48,
        title: 'Exposição de Arte Urbana',
        start: new Date(2024, 11, 1, 10, 0),
        end: new Date(2024, 11, 1, 16, 0),
        desc: 'Visita à exposição de grafites e murais urbanos',
        color: 'olivedrab',
        tipo: 'Arte',
    },
    {
        id: 49,
        title: 'Apresentação de Seminário de Psicologia',
        start: new Date(2024, 12, 5, 15, 0),
        end: new Date(2024, 12, 5, 17, 0),
        desc: 'Seminário sobre psicologia positiva',
        color: 'orange',
        tipo: 'Faculdade',
    },
    {
        id: 50,
        title: 'Entrega de Projeto de Pesquisa',
        start: new Date(2024, 1,1, 9, 0),
        end: new Date(2024, 1, 1, 11, 0),
        desc: 'Prazo final para entrega do projeto de pesquisa acadêmica',
        color: 'orangered',
        tipo: 'Faculdade',
    },{
        id: 51,
        title: 'Semana da Mulher',
        start: new Date(2024, 2, 8, 0, 0),
        end: new Date(2024, 2, 9, 23, 59),
        desc: 'Celebrando e reconhecendo as conquistas das mulheres',
        color: 'pink',
        tipo: 'Semana da Mulher',
    },
    {
        id: 52,
        title: 'Festival de Arte Contemporânea',
        start: new Date(2024, 5, 15, 0, 0),
        end: new Date(2024, 5, 20, 23, 59),
        desc: 'Exibição de obras de arte modernas e performances',
        color: 'purple',
        tipo: 'Arte',
    },
    {
        id: 53,
        title: 'Retiro Espiritual',
        start: new Date(2024, 8, 1, 0, 0),
        end: new Date(2024, 8, 7, 23, 59),
        desc: 'Retiro para reflexão e meditação',
        color: 'lightblue',
        tipo: 'Retiro',
    },
    {
        id: 54,
        title: 'Congresso de Tecnologia e Inovação',
        start: new Date(2024, 9, 10, 0, 0),
        end: new Date(2024, 9, 12, 23, 59),
        desc: 'Evento com palestras e workshops sobre as últimas tendências em tecnologia',
        color: 'green',
        tipo: 'Faculdade',
    },
    {
        id: 55,
        title: 'Feira Internacional de Livros',
        start: new Date(2024, 11, 1, 0, 0),
        end: new Date(2024, 11, 4, 23, 59),
        desc: 'Evento anual com lançamentos e autógrafos de escritores renomados',
        color: 'orange',
        tipo: 'Arte',
    },
    {
        id: 56,
        title: 'Workshop de Culinária',
        start: new Date(2024, 0, 10, 0, 0),
        end: new Date(2024, 0, 14, 23, 59),
        desc: 'Curso intensivo de culinária com chefs famosos',
        color: 'red',
        tipo: 'Workshop',
    },
    {
        id: 57,
        title: 'Acampamento de Verão',
        start: new Date(2024, 1, 15, 0, 0),
        end: new Date(2024, 1, 20, 23, 59),
        desc: 'Uma semana de diversão ao ar livre e atividades recreativas',
        color: 'blue',
        tipo: 'Acampamento',
    },
    {
        id: 58,
        title: 'Feira de Ciências',
        start: new Date(2024, 3, 1, 0, 0),
        end: new Date(2024, 3, 2, 23, 59),
        desc: 'Apresentação de projetos científicos criados por alunos',
        color: 'yellow',
        tipo: 'Faculdade',
    },
    {
        id: 59,
        title: 'Curso Intensivo de Idiomas',
        start: new Date(2024, 4, 15, 0, 0),
        end: new Date(2024, 4, 18, 23, 59),
        desc: 'Uma semana de imersão em um novo idioma',
        color: 'green',
        tipo: 'Curso',
    },
    {
        id: 60,
        title: 'Festival de Cinema Independente',
        start: new Date(2024, 6, 1, 0, 0),
        end: new Date(2024, 6, 6, 23, 59),
        desc: 'Exibição de filmes independentes de todo o mundo',
        color: 'pink',
        tipo: 'Arte',
    },
    {
        id: 61,
        title: 'Competição Esportiva Intercolegial',
        start: new Date(2024, 7, 10, 0, 0),
        end: new Date(2024, 7, 13, 23, 59),
        desc: 'Torneio anual entre escolas locais',
        color: 'orange',
        tipo: 'Esportiva',
    },
    {
        id: 62,
        title: 'Conferência de Saúde Mental',
        start: new Date(2024, 9, 1, 0, 0),
        end: new Date(2024, 9, 2, 23, 59),
        desc: 'Palestras e workshops sobre saúde mental e bem-estar',
        color: 'blue',
        tipo: 'Saúde Mental',
    },
    {
        id: 63,
        title: 'Retiro de Yoga',
        start: new Date(2024, 10, 15, 0, 0),
        end: new Date(2024, 10, 16, 23, 59),
        desc: 'Semana de práticas de yoga, meditação e relaxamento',
        color: 'purple',
        tipo: 'Retiro',
    },
    {
        id: 64,
        title: 'Festival de Música Eletrônica',
        start: new Date(2024, 0, 1, 0, 0),
        end: new Date(2024, 0, 5, 23, 59),
        desc: 'Shows de DJs e performances ao vivo',
        color: 'green',
        tipo: 'Festival',
    },
    {
        id: 65,
        title: 'Expedição de Montanhismo',
        start: new Date(2024, 2, 10, 0, 0),
        end: new Date(2024, 2, 13, 23, 59),
        desc: 'Uma semana de escalada em montanhas',
        color: 'red',
        tipo: 'Montanhismo',
    },
    {
        id: 66,
        title: 'Feira de Empreendedorismo',
        start: new Date(2024, 4, 1, 0, 0),
        end: new Date(2024, 4, 3, 23, 59),
        desc: 'Exposição de startups e workshops para empreendedores',
        color: 'yellow',
        tipo: 'Feira',
    },
    {
        id: 67,
        title: 'Semana da Moda',
        start: new Date(2024, 5, 15, 0, 0),
        end: new Date(2024, 5, 17, 23, 59),
        desc: 'Desfiles de moda e eventos relacionados à indústria fashion',
        color: 'blue',
        tipo: 'Moda',
    },
    {
        id: 68,
        title: 'Academia de Verão de Artes Performáticas',
        start: new Date(2024, 7, 1, 0, 0),
        end: new Date(2024, 7, 5, 23, 59),
        desc: 'Programa intensivo de treinamento em teatro, dança e música',
        color: 'purple',
        tipo: 'Arte',
    },
    {
        id: 69,
        title: 'Festival Gastronômico',
        start: new Date(2024, 8, 10, 0, 0),
        end: new Date(2024, 8, 13, 23, 59),
        desc: 'Evento dedicado à culinária local e internacional',
        color: 'green',
        tipo: 'Festival',
    },
    {
        id: 70,
        title: 'Feira de Carreiras Universitárias',
        start: new Date(2024, 10, 1, 0, 0),
        end: new Date(2024, 10, 4, 23, 59),
        desc: 'Exposição de oportunidades de carreira e programas de estudo',
        color: 'orange',
        tipo: 'Faculdade',
    },
    {
        id: 71,
        title: 'Conferência de Sustentabilidade',
        start: new Date(2024, 11, 15, 0, 0),
        end: new Date(2024, 11, 19, 23, 59),
        desc: 'Palestras e painéis sobre práticas sustentáveis',
        color: 'blue',
        tipo: 'Conferência',
    },
    {
        id: 72,
        title: 'Retiro de Arte e Criatividade',
        start: new Date(2024, 0, 20, 0, 0),
        end: new Date(2024, 0, 23, 23, 59),
        desc: 'Semana de exploração artística e expressão criativa',
        color: 'purple',
        tipo: 'Arte',
    },
    {
        id: 73,
        title: 'Campeonato de Surf',
        start: new Date(2024, 2, 10, 0, 0),
        end: new Date(2024, 2, 12, 23, 59),
        desc: 'Competição de surf com os melhores atletas do mundo',
        color: 'green',
        tipo: 'Campeonato de Surf',
    },
    {
        id: 74,
        title: 'Festival de Comédia',
        start: new Date(2024, 3, 15, 0, 0),
        end: new Date(2024, 3, 20, 23, 59),
        desc: 'Shows de stand-up e apresentações de comediantes',
        color: 'orange',
        tipo: 'Festival',
    },
    {
        id: 75,
        title: 'Feira de Tecnologia Agrícola',
        start: new Date(2024, 5, 1, 0, 0),
        end: new Date(2024, 5, 2, 23, 59),
        desc: 'Apresentação de inovações no setor agrícola',
        color: 'blue',
        tipo: 'Feira',
    },
    {
        id: 76,
        title: 'Retiro de Meditação Vipassana',
        start: new Date(2024, 6, 10, 0, 0),
        end: new Date(2024, 6, 13, 23, 59),
        desc: 'Retiro de meditação intensiva de 10 dias',
        color: 'purple',
        tipo: 'Retiro',
    },
    {
        id: 77,
        title: 'Festival de Fotografia',
        start: new Date(2024, 8, 1, 0, 0),
        end: new Date(2024, 8, 3, 23, 59),
        desc: 'Exibição de fotografias e workshops para entusiastas da fotografia',
        color: 'green',
        tipo: 'Festival',
    },
    {
        id: 78,
        title: 'Seminário de Inteligência Artificial',
        start: new Date(2024, 9, 15, 0, 0),
        end: new Date(2024, 9, 20, 23, 59),
        desc: 'Palestras e debates sobre o futuro da inteligência artificial',
        color: 'orange',
        tipo: 'Seminário',
    },
    {
        id: 79,
        title: 'Feira de Artesanato Local',
        start: new Date(2024, 11, 10, 0, 0),
        end: new Date(2024, 11, 13, 23, 59),
        desc: 'Exposição e venda de artesanato produzido localmente',
        color: 'blue',
        tipo: 'Feira',
    },
    {
        id: 80,
        title: 'Acampamento de Inverno',
        start: new Date(2025, 0, 15, 0, 0),
        end: new Date(2025, 0, 20, 23, 59),
        desc: 'Semana de atividades ao ar livre no inverno',
        color: 'purple',
        tipo: 'Acampamento',
    }    
]

export default eventosPadrao;